# Podfile for KomgaReaderAntigravity
platform :ios, '15.0'

target 'KomgaReaderAntigravity' do
  use_frameworks!

  # OpenCV for advanced image processing (using latest available version)
  pod 'OpenCV'
  
  # Firebase/Google ML Kit (if needed for future enhancements)
  # pod 'GoogleMLKit/TextRecognition'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # Fix for OpenCV on Apple Silicon Simulators
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
